{"statusCode": 500, "body": "{\n  \"error\": \"Unable to import required dependencies:\\nnumpy: Error importing numpy: you should not try to import numpy from\\n        its source directory; please exit the numpy source tree, and relaunch\\n        your python interpreter from there.\",\n  \"traceback\": \"Traceback (most recent call last):\\n  File \\\"/var/task/test_lambda.py\\\", line 21, in lambda_handler\\n    import pandas as pd\\n  File \\\"/opt/python/pandas/__init__.py\\\", line 19, in <module>\\n    raise ImportError(\\nImportError: Unable to import required dependencies:\\nnumpy: Error importing numpy: you should not try to import numpy from\\n        its source directory; please exit the numpy source tree, and relaunch\\n        your python interpreter from there.\\n\",\n  \"python_path\": [\n    \"/var/task\",\n    \"/var/runtime\",\n    \"/opt/python\",\n    \"/var/task\",\n    \"/var/lang/lib/python39.zip\",\n    \"/var/lang/lib/python3.9\",\n    \"/var/lang/lib/python3.9/lib-dynload\",\n    \"/var/lang/lib/python3.9/site-packages\"\n  ],\n  \"working_directory\": \"/var/task\",\n  \"environment_vars\": {\n    \"AWS_LAMBDA_FUNCTION_VERSION\": \"$LATEST\",\n    \"AWS_SESSION_TOKEN\": \"IQoJb3JpZ2luX2VjEGMaCmV1LW5vcnRoLTEiRjBEAiANkbc4xYymwGUNf4LxDTjwHwowPkjYCgTj+0mIbUEMQwIgbr8/eBNv40LdRK9zX8q8PRNRdF5NOoK1rkU1NuMkiooqjAMIXBAAGgwxNjc4NzI1NTA2NzMiDGPFCt37zbifg6CyhirpAhozd9kbJjsLIABLzAOwinQt8by2pwk7MBtgpbXhgrwjre2XotTOFZ0cfG2XNDlr16GqXcWneDhkILEEnlmSAp9erIkKRuDh5GeRRM3Ygd4Zrr4sckyF1E2uXKIUWk3PRfJjpU0paXhB9StvGdmT7ZYNupZAERaNPxJIwOpFsm2zOIk5cX4l37xDijVqPSvvrEy2pPWhPYEXHooCkWoxGgvFJeJi4aIwgKDidlPw09UHUd7riH/MV0q/M/m6+5NRmrMK5y2dv8Z8aJzBNZ7sYge58UtruFDrcC68tkK5q+JvB8MdblOI8uHPJsnqjymvYyu4JzNFC7eDIr1REoZ7YkJ1rZDIMBRv078p9FYAIfHbORV/V/jquyg6XzsCSwX6v8p4y/4iH/CDDuVBaqoq1hmDxB4jN7ka+GztJveJBg1ZPslNqLseo7t0rQaxXIlV4JL4pxGantGo90UfJJKyb6g3oIqurT8G5/ww/NX0wgY6ngFy5Ft+VGZ414wjjaN9zthRgqn4PJkK7MgJvgbbxgERczQUwlH33/MqEkNb3tBG7TD/xnSr4V6C1kt6DN3ird0OtKxOU15kwtcyeYLbe9/fzBcgSAMQxWxCfjFiqOiCPuo+qH40WgW4NJnUjyqky4B0oK29dTqktkdEd/Y31wH6oqazK5m1khsRPwmFZqvfAXr19jYEA/yowMcBHIx3bQ==\",\n    \"LD_LIBRARY_PATH\": \"/var/lang/lib:/lib64:/usr/lib64:/var/runtime:/var/runtime/lib:/var/task:/var/task/lib:/opt/lib\",\n    \"LAMBDA_TASK_ROOT\": \"/var/task\",\n    \"AWS_LAMBDA_LOG_GROUP_NAME\": \"/aws/lambda/rideshare-experiment-runner\",\n    \"AWS_LAMBDA_RUNTIME_API\": \"169.254.100.1:9001\",\n    \"AWS_LAMBDA_LOG_STREAM_NAME\": \"2025/06/26/[$LATEST]5e6e218bc93649f6bc662fbbb4caae68\",\n    \"AWS_EXECUTION_ENV\": \"AWS_Lambda_python3.9\",\n    \"AWS_XRAY_DAEMON_ADDRESS\": \"169.254.100.1:2000\",\n    \"AWS_LAMBDA_FUNCTION_NAME\": \"rideshare-experiment-runner\",\n    \"PATH\": \"/var/lang/bin:/usr/local/bin:/usr/bin/:/bin:/opt/bin\",\n    \"AWS_DEFAULT_REGION\": \"eu-north-1\",\n    \"PWD\": \"/var/task\",\n    \"AWS_SECRET_ACCESS_KEY\": \"1DCnzHUEA/UGA0yjAiObHPj/4OL+jBF5qjeJo+fU\",\n    \"LANG\": \"en_US.UTF-8\",\n    \"LAMBDA_RUNTIME_DIR\": \"/var/runtime\",\n    \"AWS_LAMBDA_INITIALIZATION_TYPE\": \"on-demand\",\n    \"TZ\": \":UTC\",\n    \"AWS_REGION\": \"eu-north-1\",\n    \"AWS_ACCESS_KEY_ID\": \"ASIASOFP324IT7JPK7H7\",\n    \"SHLVL\": \"0\",\n    \"_AWS_XRAY_DAEMON_ADDRESS\": \"169.254.100.1\",\n    \"_AWS_XRAY_DAEMON_PORT\": \"2000\",\n    \"S3_BUCKET\": \"magisterka\",\n    \"PYTHONPATH\": \"/opt/python:/var/task\",\n    \"AWS_XRAY_CONTEXT_MISSING\": \"LOG_ERROR\",\n    \"_HANDLER\": \"test_lambda.lambda_handler\",\n    \"AWS_LAMBDA_FUNCTION_MEMORY_SIZE\": \"1024\",\n    \"_X_AMZN_TRACE_ID\": \"Root=1-685d2afc-2556cbea6079826259218078;Parent=64b4c63aff62706f;Sampled=0;Lineage=1:abb47631:0\"\n  }\n}", "headers": {"Content-Type": "application/json"}}